### ISSUE TITLE
https://ci.pcgamingfreaks.at/ is throwing an error

### ISSUE THREAD

**Issue by AMDBartek** [GeorgH93/PCGF_PluginLib#19]
I am not sure if this is the right place but https://ci.pcgamingfreaks.at/ is down and PCGF_PluginLib throws an error.

Server console error:
```
[13:54:46 ERROR]: [PCGF_PluginLib] The updater could not contact https://ci.pcgamingfreaks.at to check for updates!
[13:54:46 ERROR]: [PCGF_PluginLib] If this is the first time you are seeing this message, the site may be experiencing temporary downtime.
[13:54:46 ERROR]: [PCGF_PluginLib] Message: Server returned HTTP response code: 500 for URL: https://ci.pcgamingfreaks.at/job/PluginLib/lastSuccessfulBuild/api/json?tree=artifacts[relativePath,fileName],fingerprint[hash],number,timestamp,url,fullDisplayName,changeSet[items[comment]]
```

https://ci.pcgamingfreaks.at/ error:
```
java.lang.IllegalStateException: An attempt to save the global configuration was made before it was loaded
	at jenkins.model.Jenkins.save(Jenkins.java:3379)
	at jenkins.model.Jenkins.saveQuietly(Jenkins.java:3398)
	at jenkins.model.Jenkins.setSecurityRealm(Jenkins.java:2637)
	at jenkins.model.Jenkins$16.run(Jenkins.java:3342)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1129)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused: org.jvnet.hudson.reactor.ReactorException
	at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:282)
	at jenkins.InitReactorRunner.run(InitReactorRunner.java:50)
	at jenkins.model.Jenkins.executeReactor(Jenkins.java:1162)
	at jenkins.model.Jenkins.<init>(Jenkins.java:962)
	at hudson.model.Hudson.<init>(Hudson.java:85)
	at hudson.model.Hudson.<init>(Hudson.java:81)
	at hudson.WebAppMain$3.run(WebAppMain.java:295)
Caused: hudson.util.HudsonFailedToLoad
	at hudson.WebAppMain$3.run(WebAppMain.java:312)
```

This has been happening for the past 7 or so days.

**Comment by GeorgH93** [comment]
Thanks for letting me know.
Should be fixed now.
