### ISSUE TITLE
Error to load the plugin

### ISSUE THREAD

**Issue by thiagogebrimm** [GeorgH93/PCGF_PluginLib#34]
[17:32:06 ERROR]: [PCGF_PluginLib] Failed to extract "/lang/en.yml" because it does not exist!
[17:32:06 WARN]: [PCGF_PluginLib] Fallback language file failed to extract!
[17:32:06 WARN]: [PCGF_PluginLib] Failed to load item name language file!
[17:32:06 WARN]: java.util.NoSuchElementException
[17:32:06 WARN]:        at java.base/java.util.Scanner.throwFor(Scanner.java:937)
[17:32:06 WARN]:        at java.base/java.util.Scanner.next(Scanner.java:1478)
[17:32:06 WARN]:        at PCGF_PluginLib-1.0.36-SNAPSHOT.jar//at.pcgamingfreaks.yaml.YAML.load(YAML.java:123)
[17:32:06 WARN]:        at PCGF_PluginLib-1.0.36-SNAPSHOT.jar//at.pcgamingfreaks.yaml.YAML.load(YAML.java:67)
[17:32:06 WARN]:        at PCGF_PluginLib-1.0.36-SNAPSHOT.jar//at.pcgamingfreaks.yaml.YAML.<init>(YAML.java:31)
[17:32:06 WARN]:        at PCGF_PluginLib-1.0.36-SNAPSHOT.jar//at.pcgamingfreaks.Config.YamlFileManager.load(YamlFileManager.java:247)
[17:32:06 WARN]:        at PCGF_PluginLib-1.0.36-SNAPSHOT.jar//at.pcgamingfreaks.Config.Language.load(Language.java:177)
[17:32:06 WARN]:        at PCGF_PluginLib-1.0.36-SNAPSHOT.jar//at.pcgamingfreaks.Config.Language.load(Language.java:157)
[17:32:06 WARN]:        at PCGF_PluginLib-1.0.36-SNAPSHOT.jar//at.pcgamingfreaks.Config.Language.load(Language.java:145)
[17:32:06 WARN]:        at PCGF_PluginLib-1.0.36-SNAPSHOT.jar//at.pcgamingfreaks.Bukkit.ItemNameResolver.load(ItemNameResolver.java:57)
[17:32:06 WARN]:        at PCGF_PluginLib-1.0.36-SNAPSHOT.jar//at.pcgamingfreaks.PluginLib.Bukkit.ItemNameResolver.<init>(ItemNameResolver.java:48)
[17:32:06 WARN]:        at PCGF_PluginLib-1.0.36-SNAPSHOT.jar//at.pcgamingfreaks.PluginLib.Bukkit.PluginLib.onEnable(PluginLib.java:89)
[17:32:06 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[17:32:06 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[17:32:06 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
[17:32:06 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559)
[17:32:06 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473)
[17:32:06 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671)
[17:32:06 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:438)
[17:32:06 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:352)
[17:32:06 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1181)
[17:32:06 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322)
[17:32:06 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[17:32:06 ERROR]: [PCGF_PluginLib] Failed to extract "/lang/en.yml" because it does not exist!
[17:32:06 WARN]: [PCGF_PluginLib] Fallback language file failed to extract!
[17:32:06 WARN]: [PCGF_PluginLib] Failed to load language file!
[17:32:06 WARN]: java.util.NoSuchElementException
[17:32:06 WARN]:        at java.base/java.util.Scanner.throwFor(Scanner.java:937)
[17:32:06 WARN]:        at java.base/java.util.Scanner.next(Scanner.java:1478)
[17:32:06 WARN]:        at PCGF_PluginLib-1.0.36-SNAPSHOT.jar//at.pcgamingfreaks.yaml.YAML.load(YAML.java:123)
[17:32:06 WARN]:        at PCGF_PluginLib-1.0.36-SNAPSHOT.jar//at.pcgamingfreaks.yaml.YAML.load(YAML.java:67)
[17:32:06 WARN]:        at PCGF_PluginLib-1.0.36-SNAPSHOT.jar//at.pcgamingfreaks.yaml.YAML.<init>(YAML.java:31)
[17:32:06 WARN]:        at PCGF_PluginLib-1.0.36-SNAPSHOT.jar//at.pcgamingfreaks.Config.YamlFileManager.load(YamlFileManager.java:247)
[17:32:06 WARN]:        at PCGF_PluginLib-1.0.36-SNAPSHOT.jar//at.pcgamingfreaks.Config.Language.load(Language.java:177)
[17:32:06 WARN]:        at PCGF_PluginLib-1.0.36-SNAPSHOT.jar//at.pcgamingfreaks.Config.Language.load(Language.java:157)
[17:32:06 WARN]:        at PCGF_PluginLib-1.0.36-SNAPSHOT.jar//at.pcgamingfreaks.Config.Language.load(Language.java:145)
[17:32:06 WARN]:        at PCGF_PluginLib-1.0.36-SNAPSHOT.jar//at.pcgamingfreaks.PluginLib.Bukkit.PluginLib.onEnable(PluginLib.java:92)
[17:32:06 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[17:32:06 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[17:32:06 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
[17:32:06 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559)
[17:32:06 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473)
[17:32:06 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671)
[17:32:06 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:438)
[17:32:06 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:352)
[17:32:06 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1181)
[17:32:06 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322)
[17:32:06 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by GeorgH93** [comment]
[This build](https://ci.pcgamingfreaks.at/job/PluginLib/594/artifact/target/PCGF_PluginLib-1.0.36-SNAPSHOT.jar) should fix it.
