### ISSUE TITLE
Bug on Purpur 1.19.3 kernel version - build_1920

### ISSUE THREAD

**Issue by TheFaik** [GeorgH93/PCGF_PluginLib#45]
After updating Paper to separate its plugins from bukkit plugins, a bug occurs on the fork of purpur 1.19.3 build_1920
![изображение](https://user-images.githubusercontent.com/99492973/221124801-281c7610-c366-4cd6-8ad1-df420fc0e7c7.png)
`[17:58:00] [ServerMain/ERROR]: [io.papermc.paper.plugin.provider.source.DirectoryProviderSource] Error loading plugin: Directory 'plugins\PCGF_PluginLib-1.0.39-SNAPSHOT.jar' failed to load!
java.lang.RuntimeException: Directory 'plugins\PCGF_PluginLib-1.0.39-SNAPSHOT.jar' failed to load!
	at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:59) ~[purpur-1.19.3.jar:git-Purpur-1920]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.lambda$registerProviders$2(DirectoryProviderSource.java:32) ~[purpur-1.19.3.jar:git-Purpur-1920]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1921) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:30) ~[purpur-1.19.3.jar:git-Purpur-1920]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:14) ~[purpur-1.19.3.jar:git-Purpur-1920]
	at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[purpur-1.19.3.jar:git-Purpur-1920]
	at net.minecraft.server.Main.main(Main.java:119) ~[purpur-1.19.3.jar:git-Purpur-1920]
	at org.bukkit.craftbukkit.Main.main(Main.java:316) ~[purpur-1.19.3.jar:git-Purpur-1920]
	at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: org.bukkit.plugin.InvalidPluginException: java.lang.RuntimeException: Could not copy 'plugins\update\PCGF_PluginLib-1.0.39-SNAPSHOT.jar' to 'plugins\PCGF_PluginLib-1.0.39-SNAPSHOT.jar' in update plugin process
	at io.papermc.paper.plugin.provider.source.FileProviderSource.checkUpdate(FileProviderSource.java:95) ~[purpur-1.19.3.jar:git-Purpur-1920]
	at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:49) ~[purpur-1.19.3.jar:git-Purpur-1920]
	... 19 more
Caused by: java.lang.RuntimeException: Could not copy 'plugins\update\PCGF_PluginLib-1.0.39-SNAPSHOT.jar' to 'plugins\PCGF_PluginLib-1.0.39-SNAPSHOT.jar' in update plugin process
	at io.papermc.paper.plugin.provider.source.FileProviderSource.checkUpdate(FileProviderSource.java:85) ~[purpur-1.19.3.jar:git-Purpur-1920]
	at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:49) ~[purpur-1.19.3.jar:git-Purpur-1920]
	... 19 more
Caused by: java.nio.file.FileSystemException: plugins\PCGF_PluginLib-1.0.39-SNAPSHOT.jar: Процесс не может получить доступ к файлу, так как этот файл занят другим процессом
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at sun.nio.fs.WindowsFileCopy.copy(WindowsFileCopy.java:171) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.copy(WindowsFileSystemProvider.java:284) ~[?:?]
	at java.nio.file.Files.copy(Files.java:1304) ~[?:?]
	at io.papermc.paper.plugin.provider.source.FileProviderSource.checkUpdate(FileProviderSource.java:83) ~[purpur-1.19.3.jar:git-Purpur-1920]
	at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:49) ~[purpur-1.19.3.jar:git-Purpur-1920]
	... 19 more`

**Comment by GeorgH93** [comment]
The exception says that it could not delete the old `PCGF_PluginLib-1.0.39-SNAPSHOT.jar` to replace it with the new one in the update folder.
Assuming you and your anti virus don't have the file open, I would guess this is just another bug with their new plugin loading logic.
You should be able to fix it by simply moving the `PCGF_PluginLib-1.0.39-SNAPSHOT.jar` from the update directory to the plugins directory manually.

**Comment by FunkyNico** [comment]
Hello, i have the same problem. Log: https://pastebin.ubuntu.com/p/9n9YHDQkTb/ (i don't have an update folder)

Server: Purpur version git-Purpur-1920 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 1d7602d on HEAD).

Thanks.

**Comment by GeorgH93** [comment]
> Hello, i have the same problem. Log: https://pastebin.ubuntu.com/p/9n9YHDQkTb/ (i don't have an update folder)
> 
> Server: Purpur version git-Purpur-1920 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 1d7602d on HEAD).
> 
> Thanks.

It's in the plugins directory.
